apiVersion: v1 #version of this Service kind Object
kind: Service #kind of Kube obk we want to create
metadata: #data about data, about our service
  name: backend #dns name
spec: #configure this service obj
  selector: #identifies which other resources should be controller or connected by this resource/obj
    #which pods should be part of this service
    #service expose pods to the outside world
    app: simple-example #label of that pod we want to control/connect with
  ports: # which ports to be exposed
    - protocol: 'TCP'
    - port: 8081 # port to be exposed
    - targetPort: 8080 #port inside the container
    #many ports etc
  type: LoadBalancer #Type for the Service, external or internal ip, ClusterIp for the cluster, NodePort for the workerNode ip, and LoadBalancer for the outsideWorld


#minikube service backend
