apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-persistent-volume-deployment
spec:
  selector:
    matchLabels:
      app: student-persistent-volume-example
  replicas: 1
  template:
    metadata:
      labels:
        app: student-persistent-volume-example
    spec:
      containers:
        - name: student-persistent-volume
          image: cinevacineva/student-persistent-volume
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: student-persistent-volume-service
spec:
  selector:
    app: student-persistent-volume-example
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: NodePort

  #minikube docker-env | Invoke-Expression
